language: python
sudo: false
python:
  - 2.7
#  - 3.4
#  - 3.5
#  - 3.6
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - pip install future
  - pip install pytest-cov codecov
install:
  - python setup.py develop
script:
  - py.test tests --cov atom
after_success:
  - codecov
