..
   This file holds some common substitutions (mainly for referencing code).
   To use it add the directive include:: substitutions.rst at the beginning of
   the file.

.. ============================================================================
.. Atom substitutions
.. ============================================================================

.. |Atom| replace:: :py:class:`~atom.atom.Atom`

.. |Atom.observe| replace:: :py:class:`~atom.atom.Atom.observe`

.. |Atom.unobserve| replace:: :py:class:`~atom.atom.Atom.unobserve`

.. |add_static_observer| replace:: :py:class:`~atom.catom.Member.add_static_observer`

.. |remove_static_observer| replace:: :py:class:`~atom.catom.Member.remove_static_observer`

.. |Value| replace:: :py:class:`~atom.scalars.Value`

.. |Int| replace:: :py:class:`~atom.scalars.Int`

.. |Long| replace:: :py:class:`~atom.scalars.Long`

.. |Float| replace:: :py:class:`~atom.scalars.Float`

.. |Str| replace:: :py:class:`~atom.scalars.Str`

.. |Bytes| replace:: :py:class:`~atom.scalars.Bytes`

.. |Unicode| replace:: :py:class:`~atom.scalars.Unicode`

.. |Enum| replace:: :py:class:`~atom.enum.Enum`

.. |Typed| replace:: :py:class:`~atom.typed.Typed`

.. |ForwardTyped| replace:: :py:class:`~atom.typed.ForwardTyped`

.. |Instance| replace:: :py:class:`~atom.instance.Instance`

.. |ForwardInstance| replace:: :py:class:`~atom.instance.ForwardInstance`

.. |Subclass| replace:: :py:class:`~atom.subclass.Subclass`

.. |ForwardSubclass| replace:: :py:class:`~atom.subclass.ForwardSubclass`

.. |Tuple| replace:: :py:class:`~atom.tuple.Tuple`

.. |List| replace:: :py:class:`~atom.list.List`

.. |ContainerList| replace:: :py:class:`~atom.list.ContainerList`

.. |Dict| replace:: :py:class:`~atom.dict.Dict`

.. |Delegator| replace:: :py:class:`~atom.delegator.Delegator`

.. |Event| replace:: :py:class:`~atom.event.Event`

.. |bind| replace:: :py:meth:`~atom.event.Event.bind`

.. |unbind| replace:: :py:meth:`~atom.event.Event.unbind`

.. |Signal| replace:: :py:class:`~atom.signal.Signal`

.. |connect| replace:: :py:meth:`~atom.signal.Signal.connect`

.. |disconnect| replace:: :py:meth:`~atom.signal.Signal.disconnect`

.. |Coerced| replace:: :py:class:`~atom.coerced.Coerced`

.. |Property| replace:: :py:class:`~atom.property.Property`

.. |observe| replace:: :py:class:`~atom.atom.observe`

.. |set_default| replace:: :py:class:`~atom.atom.set_default`

.. |atomref| replace:: :py:class:`~atom.catom.atomref`

.. |sortedmap| replace:: :py:class:`~atom.datastructures.sortedmap.sortedmap`
